/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifiedRouteImport } from './routes/verified'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedTrailingStopRouteImport } from './routes/_authenticated/trailing-stop'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicNotifySignupRouteImport } from './routes/api/public/notify-signup'
import { Route as AuthenticatedChartSymbolRouteImport } from './routes/_authenticated/chart.$symbol'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VerifiedRoute = VerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrailingStopRoute =
  AuthenticatedTrailingStopRouteImport.update({
    id: '/trailing-stop',
    path: '/trailing-stop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifySignupRoute = ApiPublicNotifySignupRouteImport.update({
  id: '/api/public/notify-signup',
  path: '/api/public/notify-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChartSymbolRoute =
  AuthenticatedChartSymbolRouteImport.update({
    id: '/chart/$symbol',
    path: '/chart/$symbol',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verified': typeof VerifiedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trailing-stop': typeof AuthenticatedTrailingStopRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verified': typeof VerifiedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trailing-stop': typeof AuthenticatedTrailingStopRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/promo': typeof PromoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verified': typeof VerifiedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trailing-stop': typeof AuthenticatedTrailingStopRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/chart/$symbol': typeof AuthenticatedChartSymbolRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/promo'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verified'
    | '/dashboard'
    | '/profile'
    | '/referral'
    | '/support'
    | '/trailing-stop'
    | '/upgrade'
    | '/watchlist'
    | '/email/unsubscribe'
    | '/admin/payments'
    | '/chart/$symbol'
    | '/api/public/notify-signup'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/promo'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verified'
    | '/dashboard'
    | '/profile'
    | '/referral'
    | '/support'
    | '/trailing-stop'
    | '/upgrade'
    | '/watchlist'
    | '/email/unsubscribe'
    | '/admin/payments'
    | '/chart/$symbol'
    | '/api/public/notify-signup'
    | '/lovable/email/suppression'
    | '/admin'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/promo'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verified'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/support'
    | '/_authenticated/trailing-stop'
    | '/_authenticated/upgrade'
    | '/_authenticated/watchlist'
    | '/email/unsubscribe'
    | '/_authenticated/admin/payments'
    | '/_authenticated/chart/$symbol'
    | '/api/public/notify-signup'
    | '/lovable/email/suppression'
    | '/_authenticated/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PromoRoute: typeof PromoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifiedRoute: typeof VerifiedRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicNotifySignupRoute: typeof ApiPublicNotifySignupRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verified': {
      id: '/verified'
      path: '/verified'
      fullPath: '/verified'
      preLoaderRoute: typeof VerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trailing-stop': {
      id: '/_authenticated/trailing-stop'
      path: '/trailing-stop'
      fullPath: '/trailing-stop'
      preLoaderRoute: typeof AuthenticatedTrailingStopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-signup': {
      id: '/api/public/notify-signup'
      path: '/api/public/notify-signup'
      fullPath: '/api/public/notify-signup'
      preLoaderRoute: typeof ApiPublicNotifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chart/$symbol': {
      id: '/_authenticated/chart/$symbol'
      path: '/chart/$symbol'
      fullPath: '/chart/$symbol'
      preLoaderRoute: typeof AuthenticatedChartSymbolRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrailingStopRoute: typeof AuthenticatedTrailingStopRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedChartSymbolRoute: typeof AuthenticatedChartSymbolRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrailingStopRoute: AuthenticatedTrailingStopRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedChartSymbolRoute: AuthenticatedChartSymbolRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PromoRoute: PromoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifiedRoute: VerifiedRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicNotifySignupRoute: ApiPublicNotifySignupRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
